title: Hongyan Wei's Homepage
page-top-title: Hongyan Wei
top-section-bg-text: Computer Science
home-subtitle: Hongyan Wei&ensp;|&ensp;魏鸿雁
copyright-text: '&copy; Hongyan Wei 2024-2025. All Rights Reserved.'
